using WhatsAppCampaignApi.Models.Enums;

namespace WhatsAppCampaignApi.Services.Email;

/// <summary>One email, fully rendered and ready to hand to a provider.</summary>
public sealed record EmailMessage
{
    public required EmailAddress From { get; init; }

    public EmailAddress? ReplyTo { get; init; }

    public required IReadOnlyList<EmailAddress> To { get; init; }

    public IReadOnlyList<EmailAddress> Cc { get; init; } = [];

    /// <summary>
    /// Blind recipients. Deliberately kept out of the MIME headers — see MimeMessageBuilder —
    /// and delivered through the SMTP envelope instead, so a blind recipient is never disclosed.
    /// </summary>
    public IReadOnlyList<EmailAddress> Bcc { get; init; } = [];

    public required string Subject { get; init; }

    public string? HtmlBody { get; init; }

    /// <summary>
    /// Plain-text alternative. Not optional in practice: a message with no text part looks like
    /// bulk mail to most spam filters, and is unreadable in clients with images and HTML off.
    /// The builder derives one from the HTML when none is supplied.
    /// </summary>
    public string? TextBody { get; init; }

    public IReadOnlyList<EmailAttachment> Attachments { get; init; } = [];

    /// <summary>
    /// Extra headers — the unsubscribe pair, and our own correlation id. Applied last, so they
    /// win over anything the builder would otherwise set.
    /// </summary>
    public IReadOnlyDictionary<string, string> Headers { get; init; } = new Dictionary<string, string>();

    /// <summary>
    /// The Message-ID to stamp on this message. Generated by us rather than by the provider,
    /// because it is what an inbound reply's In-Reply-To is later matched against — letting the
    /// provider choose would make reply threading guesswork.
    /// </summary>
    public string? MessageId { get; init; }

    /// <summary>Set when this message is a reply, so it threads in the recipient's client.</summary>
    public string? InReplyTo { get; init; }

    public string? ReferencesHeader { get; init; }

    /// <summary>
    /// Provider-side tags, echoed back on event notifications. Useful for attributing an event
    /// to a campaign even before our own correlation row is committed.
    /// </summary>
    public IReadOnlyDictionary<string, string> Tags { get; init; } = new Dictionary<string, string>();

    /// <summary>Every envelope recipient: who the provider is actually told to deliver to.</summary>
    public IEnumerable<EmailAddress> AllRecipients => To.Concat(Cc).Concat(Bcc);
}

/// <param name="Address">The address itself.</param>
/// <param name="DisplayName">Optional friendly name.</param>
public sealed record EmailAddress(string Address, string? DisplayName = null)
{
    public override string ToString() =>
        string.IsNullOrWhiteSpace(DisplayName) ? Address : $"{DisplayName} <{Address}>";
}

/// <param name="FileName">Name shown to the recipient.</param>
/// <param name="ContentType">MIME type. Misreporting it is what makes attachments unopenable.</param>
/// <param name="Content">The bytes.</param>
/// <param name="ContentId">Set for images referenced inline from the HTML by cid:.</param>
public sealed record EmailAttachment(
    string FileName,
    string ContentType,
    byte[] Content,
    string? ContentId = null);

/// <summary>
/// The outcome of one send attempt.
///
/// <para>
/// <see cref="IsTransient"/> is the field that matters operationally: it is what the queue uses to
/// decide between retrying with backoff and dead-lettering. Getting it wrong in one direction
/// wastes send quota re-attempting a permanently rejected address; in the other, it throws away
/// mail that a throttled provider would have accepted a second later.
/// </para>
/// </summary>
public sealed record EmailSendResult
{
    public bool Success { get; init; }

    /// <summary>The provider's id for the accepted message — the key delivery events arrive under.</summary>
    public string? ProviderMessageId { get; init; }

    public string? ErrorCode { get; init; }

    public string? ErrorMessage { get; init; }

    public bool IsTransient { get; init; }

    /// <summary>A provider-specified delay to honour instead of the computed backoff.</summary>
    public TimeSpan? RetryAfter { get; init; }

    public static EmailSendResult Sent(string providerMessageId) =>
        new() { Success = true, ProviderMessageId = providerMessageId };

    public static EmailSendResult Failed(
        string errorMessage,
        bool isTransient,
        string? errorCode = null,
        TimeSpan? retryAfter = null) =>
        new()
        {
            Success = false,
            ErrorMessage = errorMessage,
            ErrorCode = errorCode,
            IsTransient = isTransient,
            RetryAfter = retryAfter
        };
}

/// <summary>
/// The resolved, decrypted settings a provider needs for one send.
///
/// <para>
/// Credentials are decrypted into this object and nowhere else. It is never serialised, never
/// logged and never returned from an API, which keeps the window in which a plaintext secret
/// exists to a single provider call.
/// </para>
/// </summary>
public sealed record EmailProviderContext
{
    public required int EmailConfigurationId { get; init; }

    public int? ConnectionId { get; init; }

    public required EmailProviderType Provider { get; init; }

    // ── SMTP ─────────────────────────────────────────────────────────────────────────────────
    public string? SmtpHost { get; init; }

    public int? SmtpPort { get; init; }

    public SmtpSecurityMode SmtpSecurity { get; init; }

    public string? SmtpUsername { get; init; }

    public string? SmtpPassword { get; init; }

    // ── Defaults ─────────────────────────────────────────────────────────────────────────────
    public string? DefaultFromName { get; init; }

    public string? DefaultFromEmail { get; init; }

    public string? DefaultReplyTo { get; init; }
}

/// <summary>
/// What a provider can do. Lets callers degrade honestly rather than assume — an SMTP connection
/// cannot report bounces via webhook or provision DKIM, and the UI should say so instead of
/// showing a domain-verification screen that will never complete.
/// </summary>
public sealed record EmailProviderCapabilities
{
    public bool SupportsEventWebhooks { get; init; }

    public bool SupportsDkimProvisioning { get; init; }

    public bool SupportsSuppressionApi { get; init; }

    public bool SupportsInboundReceiving { get; init; }

    /// <summary>Hard message-size ceiling, including encoded attachments.</summary>
    public int MaxMessageBytes { get; init; }
}

/// <param name="Success">Whether the credentials and endpoint actually work.</param>
/// <param name="Message">
/// Operator-facing detail. Must explain what to change — "the server rejected the username or
/// password (535)" is actionable, "request failed" is not.
/// </param>
/// <param name="Details">Optional extras, such as the server's greeting or advertised size limit.</param>
public sealed record EmailProviderTestResult(
    bool Success,
    string Message,
    IReadOnlyDictionary<string, string>? Details = null)
{
    public static EmailProviderTestResult Ok(string message, IReadOnlyDictionary<string, string>? details = null) =>
        new(true, message, details);

    public static EmailProviderTestResult Fail(string message) => new(false, message);
}
