export interface CountryInfo {
  code: string
  name: string
  dialCode: string
  minDigits: number
  maxDigits: number
  flag?: string
}

export const getFlagEmoji = (countryCode: string): string => {
  if (!countryCode || countryCode.length !== 2) return '🏳️'
  const codePoints = countryCode
    .toUpperCase()
    .split('')
    .map((char) => 127397 + char.charCodeAt(0))
  return String.fromCodePoint(...codePoints)
}

export const ALL_COUNTRIES: CountryInfo[] = [
  { code: 'IN', name: 'India', dialCode: '+91', minDigits: 10, maxDigits: 10 },
  { code: 'US', name: 'United States', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', minDigits: 10, maxDigits: 10 },
  { code: 'CA', name: 'Canada', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'AU', name: 'Australia', dialCode: '+61', minDigits: 9, maxDigits: 9 },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', minDigits: 9, maxDigits: 10 },
  { code: 'SG', name: 'Singapore', dialCode: '+65', minDigits: 8, maxDigits: 8 },
  { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', minDigits: 9, maxDigits: 9 },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', minDigits: 9, maxDigits: 9 },
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', minDigits: 9, maxDigits: 9 },
  { code: 'AX', name: 'Åland Islands', dialCode: '+358', minDigits: 7, maxDigits: 10 },
  { code: 'AL', name: 'Albania', dialCode: '+355', minDigits: 8, maxDigits: 9 },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', minDigits: 9, maxDigits: 9 },
  { code: 'AS', name: 'American Samoa', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'AD', name: 'Andorra', dialCode: '+376', minDigits: 6, maxDigits: 6 },
  { code: 'AO', name: 'Angola', dialCode: '+244', minDigits: 9, maxDigits: 9 },
  { code: 'AI', name: 'Anguilla', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'AR', name: 'Argentina', dialCode: '+54', minDigits: 10, maxDigits: 10 },
  { code: 'AM', name: 'Armenia', dialCode: '+374', minDigits: 8, maxDigits: 8 },
  { code: 'AW', name: 'Aruba', dialCode: '+297', minDigits: 7, maxDigits: 7 },
  { code: 'AT', name: 'Austria', dialCode: '+43', minDigits: 10, maxDigits: 11 },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', minDigits: 9, maxDigits: 9 },
  { code: 'BS', name: 'Bahamas', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', minDigits: 8, maxDigits: 8 },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', minDigits: 10, maxDigits: 10 },
  { code: 'BB', name: 'Barbados', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'BY', name: 'Belarus', dialCode: '+375', minDigits: 9, maxDigits: 9 },
  { code: 'BE', name: 'Belgium', dialCode: '+32', minDigits: 9, maxDigits: 9 },
  { code: 'BZ', name: 'Belize', dialCode: '+501', minDigits: 7, maxDigits: 7 },
  { code: 'BJ', name: 'Benin', dialCode: '+229', minDigits: 8, maxDigits: 8 },
  { code: 'BM', name: 'Bermuda', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'BT', name: 'Bhutan', dialCode: '+975', minDigits: 8, maxDigits: 8 },
  { code: 'BO', name: 'Bolivia', dialCode: '+591', minDigits: 8, maxDigits: 8 },
  { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', minDigits: 8, maxDigits: 8 },
  { code: 'BW', name: 'Botswana', dialCode: '+267', minDigits: 8, maxDigits: 8 },
  { code: 'BR', name: 'Brazil', dialCode: '+55', minDigits: 10, maxDigits: 11 },
  { code: 'BN', name: 'Brunei', dialCode: '+673', minDigits: 7, maxDigits: 7 },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359', minDigits: 8, maxDigits: 9 },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', minDigits: 8, maxDigits: 8 },
  { code: 'BI', name: 'Burundi', dialCode: '+257', minDigits: 8, maxDigits: 8 },
  { code: 'KH', name: 'Cambodia', dialCode: '+855', minDigits: 8, maxDigits: 9 },
  { code: 'CM', name: 'Cameroon', dialCode: '+237', minDigits: 9, maxDigits: 9 },
  { code: 'CV', name: 'Cape Verde', dialCode: '+238', minDigits: 7, maxDigits: 7 },
  { code: 'KY', name: 'Cayman Islands', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236', minDigits: 8, maxDigits: 8 },
  { code: 'TD', name: 'Chad', dialCode: '+235', minDigits: 8, maxDigits: 8 },
  { code: 'CL', name: 'Chile', dialCode: '+56', minDigits: 9, maxDigits: 9 },
  { code: 'CN', name: 'China', dialCode: '+86', minDigits: 11, maxDigits: 11 },
  { code: 'CO', name: 'Colombia', dialCode: '+57', minDigits: 10, maxDigits: 10 },
  { code: 'KM', name: 'Comoros', dialCode: '+269', minDigits: 7, maxDigits: 7 },
  { code: 'CG', name: 'Congo', dialCode: '+242', minDigits: 9, maxDigits: 9 },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', minDigits: 8, maxDigits: 8 },
  { code: 'HR', name: 'Croatia', dialCode: '+385', minDigits: 8, maxDigits: 9 },
  { code: 'CU', name: 'Cuba', dialCode: '+53', minDigits: 8, maxDigits: 8 },
  { code: 'CY', name: 'Cyprus', dialCode: '+357', minDigits: 8, maxDigits: 8 },
  { code: 'CZ', name: 'Czech Republic', dialCode: '+420', minDigits: 9, maxDigits: 9 },
  { code: 'DK', name: 'Denmark', dialCode: '+45', minDigits: 8, maxDigits: 8 },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253', minDigits: 8, maxDigits: 8 },
  { code: 'DM', name: 'Dominica', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', minDigits: 9, maxDigits: 9 },
  { code: 'EG', name: 'Egypt', dialCode: '+20', minDigits: 10, maxDigits: 10 },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', minDigits: 8, maxDigits: 8 },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', minDigits: 9, maxDigits: 9 },
  { code: 'ER', name: 'Eritrea', dialCode: '+291', minDigits: 7, maxDigits: 7 },
  { code: 'EE', name: 'Estonia', dialCode: '+372', minDigits: 7, maxDigits: 8 },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', minDigits: 9, maxDigits: 9 },
  { code: 'FJ', name: 'Fiji', dialCode: '+679', minDigits: 7, maxDigits: 7 },
  { code: 'FI', name: 'Finland', dialCode: '+358', minDigits: 9, maxDigits: 10 },
  { code: 'FR', name: 'France', dialCode: '+33', minDigits: 9, maxDigits: 9 },
  { code: 'GA', name: 'Gabon', dialCode: '+241', minDigits: 8, maxDigits: 8 },
  { code: 'GM', name: 'Gambia', dialCode: '+220', minDigits: 7, maxDigits: 7 },
  { code: 'GE', name: 'Georgia', dialCode: '+995', minDigits: 9, maxDigits: 9 },
  { code: 'DE', name: 'Germany', dialCode: '+49', minDigits: 10, maxDigits: 11 },
  { code: 'GH', name: 'Ghana', dialCode: '+233', minDigits: 9, maxDigits: 9 },
  { code: 'GI', name: 'Gibraltar', dialCode: '+350', minDigits: 8, maxDigits: 8 },
  { code: 'GR', name: 'Greece', dialCode: '+30', minDigits: 10, maxDigits: 10 },
  { code: 'GD', name: 'Grenada', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', minDigits: 8, maxDigits: 8 },
  { code: 'GN', name: 'Guinea', dialCode: '+224', minDigits: 9, maxDigits: 9 },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', minDigits: 9, maxDigits: 9 },
  { code: 'GY', name: 'Guyana', dialCode: '+592', minDigits: 7, maxDigits: 7 },
  { code: 'HT', name: 'Haiti', dialCode: '+509', minDigits: 8, maxDigits: 8 },
  { code: 'HN', name: 'Honduras', dialCode: '+504', minDigits: 8, maxDigits: 8 },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', minDigits: 8, maxDigits: 8 },
  { code: 'HU', name: 'Hungary', dialCode: '+36', minDigits: 9, maxDigits: 9 },
  { code: 'IS', name: 'Iceland', dialCode: '+354', minDigits: 7, maxDigits: 7 },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', minDigits: 9, maxDigits: 12 },
  { code: 'IR', name: 'Iran', dialCode: '+98', minDigits: 10, maxDigits: 10 },
  { code: 'IQ', name: 'Iraq', dialCode: '+964', minDigits: 10, maxDigits: 10 },
  { code: 'IE', name: 'Ireland', dialCode: '+353', minDigits: 9, maxDigits: 9 },
  { code: 'IL', name: 'Israel', dialCode: '+972', minDigits: 9, maxDigits: 9 },
  { code: 'IT', name: 'Italy', dialCode: '+39', minDigits: 10, maxDigits: 10 },
  { code: 'JM', name: 'Jamaica', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'JP', name: 'Japan', dialCode: '+81', minDigits: 10, maxDigits: 10 },
  { code: 'JO', name: 'Jordan', dialCode: '+962', minDigits: 9, maxDigits: 9 },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', minDigits: 10, maxDigits: 10 },
  { code: 'KE', name: 'Kenya', dialCode: '+254', minDigits: 9, maxDigits: 9 },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', minDigits: 8, maxDigits: 8 },
  { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', minDigits: 9, maxDigits: 9 },
  { code: 'LA', name: 'Laos', dialCode: '+856', minDigits: 9, maxDigits: 10 },
  { code: 'LV', name: 'Latvia', dialCode: '+371', minDigits: 8, maxDigits: 8 },
  { code: 'LB', name: 'Lebanon', dialCode: '+961', minDigits: 7, maxDigits: 8 },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', minDigits: 8, maxDigits: 8 },
  { code: 'LR', name: 'Liberia', dialCode: '+231', minDigits: 7, maxDigits: 8 },
  { code: 'LY', name: 'Libya', dialCode: '+218', minDigits: 9, maxDigits: 9 },
  { code: 'LI', name: 'Liechtenstein', dialCode: '+423', minDigits: 7, maxDigits: 7 },
  { code: 'LT', name: 'Lithuania', dialCode: '+370', minDigits: 8, maxDigits: 8 },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', minDigits: 9, maxDigits: 9 },
  { code: 'MO', name: 'Macau', dialCode: '+853', minDigits: 8, maxDigits: 8 },
  { code: 'MK', name: 'Macedonia', dialCode: '+389', minDigits: 8, maxDigits: 8 },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', minDigits: 9, maxDigits: 9 },
  { code: 'MW', name: 'Malawi', dialCode: '+265', minDigits: 9, maxDigits: 9 },
  { code: 'MV', name: 'Maldives', dialCode: '+960', minDigits: 7, maxDigits: 7 },
  { code: 'ML', name: 'Mali', dialCode: '+223', minDigits: 8, maxDigits: 8 },
  { code: 'MT', name: 'Malta', dialCode: '+356', minDigits: 8, maxDigits: 8 },
  { code: 'MR', name: 'Mauritania', dialCode: '+222', minDigits: 8, maxDigits: 8 },
  { code: 'MU', name: 'Mauritius', dialCode: '+230', minDigits: 8, maxDigits: 8 },
  { code: 'MX', name: 'Mexico', dialCode: '+52', minDigits: 10, maxDigits: 10 },
  { code: 'MD', name: 'Moldova', dialCode: '+373', minDigits: 8, maxDigits: 8 },
  { code: 'MC', name: 'Monaco', dialCode: '+377', minDigits: 8, maxDigits: 9 },
  { code: 'MN', name: 'Mongolia', dialCode: '+976', minDigits: 8, maxDigits: 8 },
  { code: 'ME', name: 'Montenegro', dialCode: '+382', minDigits: 8, maxDigits: 8 },
  { code: 'MA', name: 'Morocco', dialCode: '+212', minDigits: 9, maxDigits: 9 },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', minDigits: 9, maxDigits: 9 },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', minDigits: 8, maxDigits: 9 },
  { code: 'NA', name: 'Namibia', dialCode: '+264', minDigits: 9, maxDigits: 9 },
  { code: 'NP', name: 'Nepal', dialCode: '+977', minDigits: 10, maxDigits: 10 },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', minDigits: 9, maxDigits: 9 },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', minDigits: 8, maxDigits: 9 },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', minDigits: 8, maxDigits: 8 },
  { code: 'NE', name: 'Niger', dialCode: '+227', minDigits: 8, maxDigits: 8 },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', minDigits: 10, maxDigits: 10 },
  { code: 'NO', name: 'Norway', dialCode: '+47', minDigits: 8, maxDigits: 8 },
  { code: 'OM', name: 'Oman', dialCode: '+968', minDigits: 8, maxDigits: 8 },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', minDigits: 10, maxDigits: 10 },
  { code: 'PS', name: 'Palestine', dialCode: '+970', minDigits: 9, maxDigits: 9 },
  { code: 'PA', name: 'Panama', dialCode: '+507', minDigits: 8, maxDigits: 8 },
  { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', minDigits: 8, maxDigits: 8 },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', minDigits: 9, maxDigits: 9 },
  { code: 'PE', name: 'Peru', dialCode: '+51', minDigits: 9, maxDigits: 9 },
  { code: 'PH', name: 'Philippines', dialCode: '+63', minDigits: 10, maxDigits: 10 },
  { code: 'PL', name: 'Poland', dialCode: '+48', minDigits: 9, maxDigits: 9 },
  { code: 'PT', name: 'Portugal', dialCode: '+351', minDigits: 9, maxDigits: 9 },
  { code: 'PR', name: 'Puerto Rico', dialCode: '+1', minDigits: 10, maxDigits: 10 },
  { code: 'QA', name: 'Qatar', dialCode: '+974', minDigits: 8, maxDigits: 8 },
  { code: 'RO', name: 'Romania', dialCode: '+40', minDigits: 9, maxDigits: 9 },
  { code: 'RU', name: 'Russia', dialCode: '+7', minDigits: 10, maxDigits: 10 },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', minDigits: 9, maxDigits: 9 },
  { code: 'SN', name: 'Senegal', dialCode: '+221', minDigits: 9, maxDigits: 9 },
  { code: 'RS', name: 'Serbia', dialCode: '+381', minDigits: 8, maxDigits: 9 },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', minDigits: 8, maxDigits: 8 },
  { code: 'SK', name: 'Slovakia', dialCode: '+421', minDigits: 9, maxDigits: 9 },
  { code: 'SI', name: 'Slovenia', dialCode: '+386', minDigits: 8, maxDigits: 8 },
  { code: 'SO', name: 'Somalia', dialCode: '+252', minDigits: 8, maxDigits: 9 },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', minDigits: 9, maxDigits: 9 },
  { code: 'KR', name: 'South Korea', dialCode: '+82', minDigits: 9, maxDigits: 10 },
  { code: 'ES', name: 'Spain', dialCode: '+34', minDigits: 9, maxDigits: 9 },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', minDigits: 9, maxDigits: 9 },
  { code: 'SD', name: 'Sudan', dialCode: '+249', minDigits: 9, maxDigits: 9 },
  { code: 'SE', name: 'Sweden', dialCode: '+46', minDigits: 9, maxDigits: 9 },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', minDigits: 9, maxDigits: 9 },
  { code: 'SY', name: 'Syria', dialCode: '+963', minDigits: 9, maxDigits: 9 },
  { code: 'TW', name: 'Taiwan', dialCode: '+886', minDigits: 9, maxDigits: 9 },
  { code: 'TJ', name: 'Tajikistan', dialCode: '+992', minDigits: 9, maxDigits: 9 },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255', minDigits: 9, maxDigits: 9 },
  { code: 'TH', name: 'Thailand', dialCode: '+66', minDigits: 9, maxDigits: 9 },
  { code: 'TG', name: 'Togo', dialCode: '+228', minDigits: 8, maxDigits: 8 },
  { code: 'TN', name: 'Tunisia', dialCode: '+216', minDigits: 8, maxDigits: 8 },
  { code: 'TR', name: 'Turkey', dialCode: '+90', minDigits: 10, maxDigits: 10 },
  { code: 'TM', name: 'Turkmenistan', dialCode: '+993', minDigits: 8, maxDigits: 8 },
  { code: 'UG', name: 'Uganda', dialCode: '+256', minDigits: 9, maxDigits: 9 },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', minDigits: 9, maxDigits: 9 },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', minDigits: 8, maxDigits: 8 },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', minDigits: 9, maxDigits: 9 },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', minDigits: 10, maxDigits: 10 },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', minDigits: 9, maxDigits: 10 },
  { code: 'YE', name: 'Yemen', dialCode: '+967', minDigits: 9, maxDigits: 9 },
  { code: 'ZM', name: 'Zambia', dialCode: '+260', minDigits: 9, maxDigits: 9 },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', minDigits: 9, maxDigits: 9 }
]
